package:
  name: deepcarskit
  version: 1.0.1

source:
  path: ../

requirements:
  build:
    - python
  host:
    - python
    - recbole ==1.0.1
    - numpy >=1.17.2
    - scipy ==1.6.0
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - scikit-learn >=0.23.2
    - pytorch >=1.7.0
    - colorlog==4.7.2
    - colorama==0.4.4
    - tensorboard >=2.5.0
  run:
    - python
    - recbole ==1.0.1
    - numpy >=1.17.2
    - scipy ==1.6.0
    - pandas >=1.0.5
    - tqdm >=4.48.2
    - pyyaml >=5.1.0
    - scikit-learn >=0.23.2
    - pytorch >=1.7.0
    - colorlog==4.7.2
    - colorama==0.4.4
    - tensorboard >=2.5.0
test:
  imports:
    - deepcarskit

about:
  home: https://github.com/irecsys/DeepCARSKit
  license: MIT
  summary: "A Deep Learning Based Context-Aware Recommendation Library"
  
